[workspace]
members = [
    "programs/enrg-mvp"
]
exclude = [
    "programs/enrg-profile"
]
resolver = "2"

[workspace.lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ["cfg(no_entrypoint)"] }

[profile.release]
opt-level = "z"
lto = true
debug = false
overflow-checks = true

[workspace.dependencies]
# Пинним proc-macro2 на версию, совместимую с anchor-syn 0.30.1
proc-macro2 = "=1.0.66"
crypto-common = "=0.1.6"
