#!/usr/bin/env python3
"""
Emit the caption file and the readable script for the pitch video:
    ENRG_pitch.srt   — captions, one cue per spoken beat
    narration.md     — the script with the rendered timings and on-screen text

Timings are recomputed from the cached piper output in PITCH_WORK, so this is
deterministic and does not re-synthesize anything.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import render as R  # noqa: E402


def cached(scene):
    outdir = os.path.join(R.WORK, f'tts-{scene["id"]}')
    wavs = sorted(os.path.join(outdir, f) for f in os.listdir(outdir) if f.endswith(".wav"))
    if len(wavs) != len(scene["beats"]):
        sys.exit(f'{scene["id"]}: cached TTS is incomplete - run build.sh first')
    beats = []
    for beat, wav in zip(scene["beats"], wavs):
        b = dict(beat)
        b["wav"], b["dur"] = wav, R.dur(wav)
        beats.append(b)
    return R.schedule(beats, scene["min_duration"])


def stamp(t):
    h, m = int(t // 3600), int((t % 3600) // 60)
    return f"{h:02d}:{m:02d}:{t % 60:06.3f}".replace(".", ",")


def main():
    srt, md, offset, cue = [], [], 0.0, 1
    md.append("# ENRG — pitch narration (as rendered)\n")
    md.append("> Generated by `extras.py` from `beats.json` and the measured "
              "voice-over. Timings are the rendered ones — the on-screen text of "
              "each beat appears with its line.\n")
    for scene in R.SCENES:
        beats, total = cached(scene)
        md.append(f'\n## {scene["label"]}\n')
        md.append(f'*{total:.1f}s · "{scene["headline"].replace(chr(10), " / ")}"*\n')
        md.append("| t | voice-over | on screen |")
        md.append("|---|---|---|")
        for b in beats:
            start, end = offset + b["start"], offset + b["start"] + b["dur"]
            srt.append(f"{cue}\n{stamp(start)} --> {stamp(end)}\n{b['vo']}\n")
            cue += 1
            md.append(f'| {start:6.1f}s | {b["vo"]} | {b.get("bullet", "")} |')
        offset += total
    srt.append(f"{cue}\n{stamp(offset)} --> {stamp(offset + R.META['endcard'])}\n"
               "ENRG — verification infrastructure for the physical world. "
               "github.com/AntonGrid/ENRG\n")
    md.append(f"\n## end card\n\n*{R.META['endcard']:.1f}s · logo, tagline, repository*\n")
    md.append(f"\n**Total: {offset + R.META['endcard']:.1f}s "
              f"({int((offset + R.META['endcard']) // 60)}:{(offset + R.META['endcard']) % 60:04.1f})**\n")

    here = os.path.dirname(os.path.abspath(__file__))
    open(os.path.join(here, "ENRG_pitch.srt"), "w", encoding="utf-8").write("\n".join(srt))
    open(os.path.join(here, "narration.md"), "w", encoding="utf-8").write("\n".join(md) + "\n")
    print(f"captions: {cue} cues · total {offset + R.META['endcard']:.1f}s")


if __name__ == "__main__":
    main()
