#!/usr/bin/env bash
# Vendor the NXP Plug & Trust middleware ("mini package") into vendor/se05x/.
#
# Why `vendor/` and not `lib/`: PlatformIO compiles *every* library under lib/
# for *every* environment of the project, so a vendored tree there breaks the
# esp32dev / esp32dev-ota builds (they would be compiled without the SSS include
# paths and defines). `vendor/` is added per-environment through
# `lib_extra_dirs` in the esp32dev-se050 env only.
#
# Why a script and not a committed tree: the middleware is third-party code
# (~370 KB, 105 files). Keeping it out of git keeps `git log` about our code, and
# the pin below makes the build reproducible. Redistribution *is* allowed: the
# package is BSD-3-Clause (LICENSE.txt, "Copyright 2018-2020,2024 NXP"), which is
# why vendoring was never a licensing problem — the earlier claim in
# SE050-HARDWARE-SIGNING.md that NXP's middleware is "closed, therefore not
# vendored" was wrong, and this script replaces it.
#
# Usage:
#   firmware/esp32_proof_sender/scripts/vendor-se050.sh            # pinned ref
#   SE050_MW_REF=<ref> firmware/esp32_proof_sender/scripts/vendor-se050.sh
set -euo pipefail

# Pinned upstream: NXP/plug-and-trust @ master 2026-04-22 (verified 2026-09-21).
REF="${SE050_MW_REF:-1ddf8cf0cdf9d7f77e32d7e62b19b6a58d74f5fa}"
# sha256 of the tarball we vendored; a mismatch is reported but not fatal, since
# GitHub does not promise byte-identical archives forever.
EXPECTED_SHA256="${SE050_MW_SHA256:-}"
DEST="${1:-$(cd "$(dirname "$0")/.." && pwd)/vendor/se05x}"
URL="https://codeload.github.com/NXP/plug-and-trust/tar.gz/${REF}"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "==> downloading ${URL}"
curl -sSfL --max-time 180 -o "$tmp/mw.tar.gz" "$URL"
sha256="$(sha256sum "$tmp/mw.tar.gz" | awk '{print $1}')"
echo "    sha256(tarball) = ${sha256}"
if [ -n "$EXPECTED_SHA256" ] && [ "$EXPECTED_SHA256" != "$sha256" ]; then
    echo "!!  tarball sha256 differs from the recorded one (${EXPECTED_SHA256})"
fi

tar -xzf "$tmp/mw.tar.gz" -C "$tmp"
src="$(find "$tmp" -maxdepth 1 -type d -name 'plug-and-trust-*' | head -1)"
[ -n "$src" ] || { echo "!!  unexpected archive layout"; exit 1; }

# The licence is the reason this script exists — verify it is still BSD-3-Clause.
if ! head -1 "$src/LICENSE.txt" | grep -q 'BSD 3-Clause'; then
    echo "!!  LICENSE.txt is no longer BSD 3-Clause — stop and re-read the terms:"
    head -5 "$src/LICENSE.txt"
    exit 1
fi

rm -rf "$DEST"
mkdir -p "$DEST"
# Only what the ESP32 tier needs: the SSS API + the T=1-over-I2C host library.
# Excluded on purpose (they do not compile on a bare-metal target, and the
# PlatformIO build would try to compile every .c under lib/):
#   sss/ex/src/**                      examples with their own main(); the
#                                      sss/ex/inc headers ARE kept (se05x_mw.c
#                                      includes ex_sss_objid.h)
#   sss/src/openssl/**, mbedtls/**     host crypto (ftr: HOSTCRYPTO_NONE)
#   sss/src/keystore/keystore_{openssl,pc}.c
#   hostlib/.../T1oI2C/phNxpEsePal_i2c.c   Linux PAL (linux/i2c-dev.h, fcntl)
#   hostlib/.../libCommon/nxScp/nxScp03_Com.c  SCP03 needs host crypto (AES-CMAC);
#                                      ftr says HOSTCRYPTO_NONE, so it #errors
#   hostlib/.../platform/linux/**      Raspberry Pi i2c_a7.c
#   hostlib/.../platform/rsp/**        reset helpers for a different board
#   hostlib/.../platform/generic/sm_timer.c   replaced by the Arduino port
# Everything excluded is replaced by lib/enrg_se050_port/ (committed, ours).
for d in sss hostlib; do
    cp -r "$src/$d" "$DEST/"
done
rm -rf \
    "$DEST/sss/ex/src" \
    "$DEST/sss/src/openssl" \
    "$DEST/sss/src/mbedtls" \
    "$DEST/sss/src/keystore/keystore_openssl.c" \
    "$DEST/sss/src/keystore/keystore_pc.c" \
    "$DEST/hostlib/hostLib/libCommon/smCom/T1oI2C/phNxpEsePal_i2c.c" \
    "$DEST/hostlib/hostLib/libCommon/nxScp" \
    "$DEST/hostlib/hostLib/platform/linux" \
    "$DEST/hostlib/hostLib/platform/rsp" \
    "$DEST/hostlib/hostLib/platform/generic/sm_timer.c"
for f in fsl_sss_ftr.h LICENSE.txt README.rst SCR.txt ChangeLog.md SBOM.spdx.json; do
    cp "$src/$f" "$DEST/"
done

cat > "$DEST/VERSION" <<EOF
Vendored third-party code — do not edit in place.
upstream:      https://github.com/NXP/plug-and-trust
ref:           ${REF}
fetched:       $(date -u +%Y-%m-%dT%H:%M:%SZ)
sha256(tar.gz): ${sha256}
license:       BSD-3-Clause (see LICENSE.txt, "Copyright 2018-2020,2024 NXP")
vendored by:   firmware/esp32_proof_sender/scripts/vendor-se050.sh
EOF

# The mini package ships the individual SSS headers but not the umbrella
# `sss.h` the full middleware has — and the firmware includes <sss.h>. Generate
# the umbrella here rather than editing the firmware to match the packaging.
cat > "$DEST/sss.h" <<'EOF'
/* Generated by scripts/vendor-se050.sh — umbrella for the two headers the
 * firmware actually uses. The NXP mini package has no sss.h. */
#ifndef ENRG_SE050_VENDORED_SSS_H
#define ENRG_SE050_VENDORED_SSS_H
#include <fsl_sss_api.h>
#include <fsl_sss_se05x_apis.h>
#include <fsl_sss_se05x_types.h>
#endif
EOF

# PlatformIO only compiles what looks like a library; the package root has no
# src/, so point it at the package root explicitly.
cat > "$DEST/library.json" <<EOF
{
  "name": "se05x-plug-and-trust-vendored",
  "version": "0.0.0-${REF:0:12}",
  "description": "NXP Plug & Trust mini package (BSD-3-Clause), vendored by scripts/vendor-se050.sh; the ESP32 host port lives in lib/enrg_se050_port",
  "license": "BSD-3-Clause",
  "frameworks": "*",
  "platforms": "*",
  "build": { "srcDir": "." }
}
EOF
echo "==> vendored into ${DEST}"
echo "    $(find "$DEST" -type f | wc -l) files; VERSION written"
echo
echo "Next: the ESP32 host port (I2C via Wire + sm_timer) lives in"
echo "      lib/enrg_se050_port/ and is committed — the middleware is not."
