#!/usr/bin/env bash
# ENRG — regenerate idls/enrg_profile.json (the profile IDL consumed by
# enrg-mvp's `declare_program!(enrg_profile)`).
#
# WHY A SCRIPT: enrg-profile is deliberately NOT a Cargo workspace member
# (Cargo.toml `exclude`), so `anchor idl build -p enrg-profile` cannot be used.
# The IDL must be generated by temporarily putting the crate into the workspace.
#
# WHY THE TRIM: Anchor's IDL build emits an `errors` array and an `events`
# section. `declare_program!` in enrg-mvp turns those into a second
# `#[error_code]` enum in the same crate, which breaks the enrg-mvp IDL build
# with "Multiple error definitions are not allowed". The CPI only needs
# instructions + accounts + types, so errors/events/event-types are dropped —
# exactly as the previous committed IDL was shaped.
#
# Usage: bash scripts/gen-profile-idl.sh
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

cp Cargo.toml /tmp/enrg-Cargo.toml.bak
cp Anchor.toml /tmp/enrg-Anchor.toml.bak
restore() {
  cp /tmp/enrg-Cargo.toml.bak Cargo.toml
  cp /tmp/enrg-Anchor.toml.bak Anchor.toml
  echo "restored Cargo.toml / Anchor.toml"
}
trap restore EXIT

python3 - <<'PY'
import json
s = open('Cargo.toml').read()
s = s.replace('members = [\n    "programs/enrg-mvp",\n]\nexclude = [\n    "programs/enrg-profile",\n]',
              'members = [\n    "programs/enrg-mvp",\n    "programs/enrg-profile",\n]')
open('Cargo.toml', 'w').write(s)

ID = 'enrg_profile = "78FUdpHn7pWPjnDhA8RWCsXxZq6r4wVPtCcsEKBBvhUt"'
s = open('Anchor.toml').read()
for sec in ('[programs.devnet]', '[programs.localnet]', '[programs.mainnet]'):
    i = s.index(sec) + len(sec)
    j = s.index('\n[', i)
    if 'enrg_profile' not in s[i:j]:
        s = s[:i] + s[i:j].rstrip('\n') + '\n' + ID + s[j:]
s = s.replace('members = ["programs/enrg-mvp"]\nexclude = ["programs/enrg-profile"]',
              'members = ["programs/enrg-mvp", "programs/enrg-profile"]')
open('Anchor.toml', 'w').write(s)
print('temporary workspace patch applied')
PY

# Phase 1: only the profile IDL (its crate is now a workspace member). No .so is
# needed here — the binary is built with `cargo build-sbf` (see MAINNET-RUNBOOK).
anchor idl build -p enrg-profile -o target/idl/enrg_profile.json

# Phase 2: shape it like the committed file (see the WHY above).
python3 - <<'PY'
import json
idl = json.load(open('target/idl/enrg_profile.json'))
idl['errors'] = []
idl.pop('events', None)
idl['types'] = [t for t in idl.get('types', []) if t.get('name') == 'EnergyProfile']
json.dump(idl, open('idls/enrg_profile.json', 'w'), indent=2)
open('idls/enrg_profile.json', 'a').write('\n')
print('idls/enrg_profile.json written:', [i['name'] for i in idl['instructions']])
PY

# Phase 3: restore the workspace, then rebuild enrg-mvp — its IDL build only
# succeeds with the trimmed profile IDL in place (that is the whole point).
#
# `touch` is REQUIRED: `declare_program!` reads the IDL with `fs::read`, which
# cargo does not fingerprint. Without a source change the previous expansion is
# reused and the build keeps failing with "Multiple error definitions are not
# allowed" even though the file is already trimmed.
restore
trap - EXIT
touch programs/enrg-mvp/src/lib.rs
anchor build

echo "OK: idls/enrg_profile.json regenerated and enrg-mvp rebuilt."
